### ISSUE TITLE
Could not retrieve information for site

### ISSUE THREAD

**Issue by webgobe** [akeeba/panopticon#177] opened 2023-10-25 07:21 UTC
This is the problematic site, is Joomla 3.10.12, with AdminTools installed
https://demo.webgobe.com/panopticon_api/index.php/v1/panopticon/core/update?force=1
This is the full entry from refreshsitesinfo.log:
Could not retrieve information for site #7 (Webgobe Demo 3). The server replied with the following error: Client error: `GET https://demo.webgobe.com/panopticon_api/index.php/v1/panopticon/core/update?force=1` resulted in a `404 Not Found` response: {"links":{"self":"https:\/\/demo.webgobe.com\/panopticon_api\/index.php\/v1\/panopticon\/core\/update?force=1"},"data":{ (truncated...)

**Comment by nikosdion** [comment] 2023-10-25 07:54
Nothing to do with Admin Tools.

Edit the site, change its endpoint to `https://demo.webgobe.com/index.php/panopticon_api`. Before you say it's the same, read it carefully. The `index.php` is in front now.

This is essentially a duplicate of https://github.com/akeeba/panopticon_connector_j3/issues/4

**Closed by nikosdion** 2023-10-25 07:54 UTC
Labels: duplicate

**Comment by webgobe** [comment] 2023-10-25 14:34
![image](https://github.com/akeeba/panopticon/assets/13080862/d8ce01d4-bd6a-4ac0-b899-d23df1d26d60)
No, is ot the same. the problem is illustrated by the screenshoot above: in Panopticon the API endpoint has been/and it is correctly entered

**Comment by nikosdion** [comment] 2023-10-25 14:38
Yes, it is the same issue. Read what I told you to enter once again, but more carefully this time. Did you spot the missing `index.php/` now?

**Comment by nikosdion** [comment] 2023-10-25 14:38
Also, please do NOT upload screenshots with your API key. These issues are public.

**Comment by webgobe** [comment] 2023-10-25 14:52
OK, I added the index.php, but I don't get why is needed, when the plugin on the site outputs the endpoint withouth the index.php. And it is running with SEF url's with .htaccess... Whatewer, if this fixes it, I am happy with the solution, just don't get what I did wrong.

**Comment by webgobe** [comment] 2023-10-25 14:56
Seemingly issue is fixed. Thanks!

**Comment by nikosdion** [comment] 2023-10-25 15:04
I can explain the part you don't get.

The reason you need the `index.php/` in the URL is exactly because you do **not** have a `.htaccess` file. Without either the `index.php/` or the `.htaccess` Apache wasn't able to find a file or folder called `panopticon_api` and threw its hands in the air screaming HTTP 404 Not Found! Adding the `index.php` we forced Apache to load Joomla! and let our own code handle the request.

Now, one more time, in more depth (this also helps you understand how Joomla!'s SEF URLs work under the hood).

When you have the URL `/panopticon_api` your web server (Apache) tries to find a file or folder called `panopticon_api`. What happens next, depends on whether you have a `.htaccess` file set up on your site which enables SEF URLs:
* If you **do not** have the file, or it does not have the Joomla! SEF URL code block, Apache cannot find a file or folder named `panopticon_api` and returns an HTTP 404 Not Found error.
* If you **do** have the file and it has the Joomla! SEF URL code block, Apache sees that the file or folder does not exist _but loads Joomla's index.php file instead_.

When you have the URL /index.php/panopticon_api` we are kinda cheating your eye here. We are merely asking your web server (Apache) to load the file `/index.php` which does exist; that's the `index.php` file Joomla! uses to display every front-end page. The rest of that URL, `/panopticon_api` is just an extra bit Apache shrugs at and does not try to parse.

In both of these latter cases, Apache has loaded Joomla!'s index.php file. The Panopticon plugin kicks in and looks if Joomla! was loaded with a URL which starts with `/index.php/panopticon_api` or `/panopticon_api`. In this case, it takes over control and does its own API thing — basically, it's emulating the way Joomla! itself parses SEF URLs.

Side note: Yes, that's exactly how Joomla! SEF URLs work, too! The existence of `index.php/` in front of them, or the existence of the `.htaccess` file with the SEF URLs code block, tells Apache to ignore missing files and load Joomla's `index.php` file. Once Joomla! loads, it runs its SEF URL router. That router looks at the URL path used to load the page. It tries to parse it based on the rules set up by its menu system and the routers of the components you have installed. This converts the URL path to a bunch of request parameters that Joomla! can actually understand and execute the relevant code on the site.

Web site development is like a Hollywood set. It's all cardboard, string, and duct-tape, with some carefully chosen shooting angles to produce movie magic.

**Comment by webgobe** [comment] 2023-10-25 15:45
Thank you to spend your precious time on my problem, but unless I should have a .htaccess file in some other spot too, but in the site's root, the reasoning does not stand up. I definitively HAVE a .htaccess file. (One created with the use of AdminTools's htaccess maker feature, actually). 
That's what dazzles me. I am not a rookie here, I had extensions published even in the Mambo's extension repository, and I have set up my first webserver on a SCO Linux box in 1997, so I know couple of things about  web publishing in general, and Joomla in particular. Not as much as you, of course, but let's say I am at least at an educated hobbyist level. I am mentioning it just to clarify couple of things there, to let you see more clearly who's in the other end of this dialogue.
So, this is what really dazzles me: I have a correctly  working .htaccess file - and generally, a site which is working satisfactory, at least SEF URLs wise - the Panopticon plugin outputs to me the index.php-less API endpoint - as expected, in given circumstances, and still Panopticon can access correctly only the URL which should be used in the scenario you depicted: SEF URL's turned on, no valid .htaccess.
Again, I am happy, that with this trick Panopticon seemingly work correctly. I just don't really understand what's going on. Again, I am really grateful for your effort to trying to explain the situation. Really appreciate it.  
I like the Hollywood set paradigma, BTW ;)

**Comment by nikosdion** [comment] 2023-10-25 20:23
So, if you do have a .htaccess then the problem is that something in the .htaccess may be blocking that specific URL. I have no idea why, because I am (of course) using Admin Tools Pro with .htaccess Maker in all of my sites without a problem.
