### ISSUE TITLE
Available updates - part 1

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#80] opened 2023-08-07 09:51 UTC
![image](https://github.com/akeeba/panopticon/assets/1296369/b027b2f9-de29-4c3d-bb64-9d22146bf5de)

![image](https://github.com/akeeba/panopticon/assets/1296369/9da581cb-0b8c-4f71-bcba-93d64b701596)

As you can see fro the screenshots Joomla is reporting updates available for some regular labs extensions but panopticon is not which is weird

**Comment by nikosdion** [comment] 2023-08-07 10:41
There are a few things to consider.

Results are always cached on Panopticon's side. Have you set up the Panopticon CRON job? If so, it will update the site and extensions information every approximately 15' (depending on what else it needs to do).

Does Peter use the standard Joomla! extensions updater? If he's using some plugin to inject his updates then we can't list the updates.

Panopticon only lists top level extensions and their updates, i.e. extensions which have a package ID of 0. If Peter has put his extensions under a non-zero package ID they will not be listed. This is deliberate and necessary. Otherwise you'd see a list of several hundred extensions (just core Joomla! is nearly 300 extensions!), most of which would complain there is no update site for.

**Comment by brianteeman** [comment] 2023-08-07 10:46
No idea about his stuff. I never use it. I was just t5esting on a copy of a clients site that was on my laptop (which is now powered off until a new battery arrives. I suddenly noticed that the back of the laptop was about to explode

**Comment by nikosdion** [comment] 2023-08-07 11:22
I am closing this as a duplicate of #81 since these are related and I'm going to be testing with both Peter's and Tassos' extensions anyway.

**Closed by nikosdion** 2023-08-07 11:22 UTC
