### ISSUE TITLE
balbooa components not updating

### ISSUE THREAD

**Issue by Raxiel1987** [akeeba/panopticon#222] opened 2023-11-02 12:34 UTC
i don't think it'ìs a bug but the balbooa forms and gallery not updating, they're not updating throght the exstension manager but you have to go in extension/ and update them directly from there

maybe you can see if it's possibile to update them with panopticon or you think is hard to achieve?

**Comment by nikosdion** [comment] 2023-11-02 12:52
Panopticon does not have its own extensions updater. It merely asks Joomla's extensions updater to update the selected extensions (selected either automatically based on the update rules you've set up, or manually by the user). Since you tell me that this particular extension does not update through Joomla's extensions updater, it won't be updated by Panopticon either. It's not a bug, exactly as you said.

There is a very good reason why I decided to only ever support extensions using the Joomla! extensions updater. There is no excuse anymore for any third party developer to not use the Joomla! extensions updater for their extensions.

The Joomla! extensions updater as a whole has been around since Joomla! 1.6 was released in 2010 — 13 years ago. I contributed myself the support for updating paid extensions with the Joomla! extensions updater in 2014 — 9 years ago. Managing the download keys for paid extension updates from Joomla! itself has been possible since Joomla 4.0 was released in August 2021 — 2 years ago.

**Closed by nikosdion** 2023-11-02 12:52 UTC
