### ISSUE TITLE
totp six digit code

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#467] opened 2023-12-31 11:04 UTC
This code creates an input type of number. It should be an input type of text with a filter of integer. You dont need the up/down spinner this input type creates (including negative numbers)

https://github.com/akeeba/panopticon/blob/3f92a61b9ab25309e0699b134233e363f48af68e/ViewTemplates/Mfamethods/form.blade.php#L97-L104

**Comment by nikosdion** [comment] 2023-12-31 15:03
A numeric field means that on-screen keyboards (phones, tablets, …) will display a numeric keyboard, with big touch buttons.

A generic text field with a filter means that on-screen keyboards display the generic keyboard. On iOS it means that the numeric entry is hidden behind yet another tap and even then displays small buttons.

Why note use [`inputmode`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) in the text field, you may ask. It's not supported by mobile Safari which is a good half of the users who actually need the correct entry mode for TOTP codes. I have confirmed this myself with iOS and iPadOS 17.2. I have to use a number field, even though _I do know_ it's not the appropriate field type because of Safari.

I am closing this as `wontfix` since the current implementation is still necessary because of Safari.

**Closed by nikosdion** 2023-12-31 15:03 UTC

**Comment by brianteeman** [comment] 2023-12-31 15:32
learnt something new about safari.

**Comment by brianteeman** [comment] 2023-12-31 16:05
obviously dont have an ios device to test with but browserstack (which supposedly tests on real devices) shows inputmode working on this url https://www.dofactory.com/html/inputmode

**Comment by nikosdion** [comment] 2023-12-31 23:01
It must be a _very_ new thing, and it's still not marked as officially supported. I am reluctant to use it as a result.

**Comment by brianteeman** [comment] 2023-12-31 23:20
no problem
