### ISSUE TITLE
v1.0.2 error: access extension update overview

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#210] opened 2023-10-31 19:29 UTC
after installing version 1.0.2 (update) and clear cache.
when i access the overview page extention updates i get this error:
also when i acces the core updates pages, my profile page, 
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.extensions.hasUpdates' = 1' at line 3

regarding my profile page, when i check the users and the select my user account i get the profile page and i can change and safe settings.

**Comment by nikosdion** [comment] 2023-10-31 20:26
Duplicate of already fixed https://github.com/akeeba/panopticon/issues/201

**Closed by nikosdion** 2023-10-31 20:26 UTC
Labels: duplicate
