### ISSUE TITLE
Can't save the update preference

### ISSUE THREAD

**Issue by vinespie** [akeeba/panopticon#704] opened 2024-06-11 13:40 UTC
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

In the system configuration, saving an update preference for a file type extension does not work.
After saving, the selection is lost.

### Reproduction instructions

1. Go to Administration / System configuration
2. Click on "Automatic Tasks" tab
3. Scroll down to "Extensions updates"
4. For a file type extension, choose a preference from the dropdown list and save.
5. The selection is not saved

### Expected behaviour

The update preference must be saved.

### Actual behaviour

The update preference is not saved.

### Screenshots

1- 
![image](https://github.com/akeeba/panopticon/assets/5129879/ddb21c5b-2de8-4caf-a254-bdcc7833a7ba)

4- 
![image](https://github.com/akeeba/panopticon/assets/5129879/cd26127e-691f-41c7-a0ad-a0437708040f)

### Panopticon version

1.1.3

### PHP version

8.2.20

### Database type

MySQL

### Database version

8.0.35

### Browser

Firefox

**Comment by nikosdion** [comment] 2024-06-11 14:08
I tried exactly your instructions. I changed the preferences for `file_fef`, `file_fof30`, and `file_fof40`. The changes saved just fine.

That said, there is nothing special for each extension type. The extension type is only shown for your information. What we save is the extension slug, such as `com_example`, `pkg_whatever`, `tpl_blah`, `plg_system_something`, and `file_foo` along with the update preference.

If you have more than 80 different extensions you may be unable to save anything on the System Configuration page due to a low PHP request limit. The default is 1000 which is more than plenty, but some hosts use a much lower value, typically 100, which is not enough for this use case.

**Comment by vinespie** [comment] 2024-06-11 15:31
Okay, I was able to identify my problem.
In the code, there is a check on the extension names before saving, "isvalidShortname".

\src\Model\Sysconfig.php
```
public function isvalidShortname(string $shortname): bool
{
      if (!str_contains($shortname, '_'))
      {
	      return false;
      }
      
      $parts = explode('_', $shortname, 3);
      
      if (!in_array($parts[0], ['pkg', 'com', 'plg', 'amod', 'mod', 'file', 'lib', 'tpl', 'atpl']))
      {
	      return false;
      }
      
      $noEmptyparts = array_reduce(
	      $parts,
	      fn(bool $carry, $item) => $carry && (is_string($item) && !empty($item)),
	      true
      );
      
      switch ($parts[0])
      {
	      case 'pkg':
	      case 'com':
	      case 'file':
	      case 'lib':
	      case 'mod':
	      case 'amod':
	      case 'tpl':
	      case 'atpl':
		      return count($parts) >= 2 && $noEmptyparts;
      
	      case 'plg':
		      return count($parts) >= 3 && $noEmptyparts;
      }
      
      return false;
}
```

The extension for which I want to configure the update has a name that does not start with : 'pkg', 'com', 'plg', 'amod', 'mod', 'file', 'lib', 'tpl', 'atpl'.

Is a modification of this code necessary?

**Comment by nikosdion** [comment] 2024-06-11 18:44
If this method returns `false`, your extension has an invalid internal name on your Joomla! site.

**Comment by vinespie** [comment] 2024-06-12 06:30
Alright, there are many extensions in this case and some are widely used by the community. I understand this restriction, a message or information about this case could be useful.

**Comment by nikosdion** [comment] 2024-06-12 07:42
Your statement is incorrect. Panopticon supports all the extension types Joomla! itself does. If something is using a wrong prefix (e.g. `files_` instead of `file_`) _Joomla! itself_ won't be able to update it correctly.

**Comment by brianteeman** [comment] 2024-06-12 08:05
What are the extensions?

**Comment by nikosdion** [comment] 2024-06-12 08:59
I am pretty sure that your description of the problem has nothing to do with the fact that it is a `file` extension. The type is correct there, it's `file`. This means that in the code you showed me, the first if-block doesn't return false:

```php
		if (!in_array($parts[0], ['pkg', 'com', 'plg', 'amod', 'mod', 'file', 'lib', 'tpl', 'atpl']))
		{
			return false;
		}
```


`$noEmptyparts` is true since there are no empty parts (double underscores).

The switch falls to the first case `return count($parts) >= 2 && $noEmptyparts;` which returns true since both `count($parts) >= 2` is true (we have three parts) and `$noEmptyparts` is true.

I am closing this as invalid. If you have actually usable reproduction instructions please let me know.

**Closed by nikosdion** 2024-06-12 08:59 UTC
Labels: support
