### ISSUE TITLE
feature request: add multiple 2FA options

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#194] opened 2023-10-29 05:53 UTC
Currently only webkey is available for 2FA. Can you add 2FA using authenticator to the options.

**Comment by johanpeters** [comment] 2023-10-29 05:55
and if possible set general 2FA (forced) so that every account need to set 2FA before getting access. 
same way as you build Akeeba 2FA

**Comment by nikosdion** [comment] 2023-10-29 08:16
Duplicate of https://github.com/akeeba/panopticon/issues/168

Already implemented for 1.0.2

**Closed by nikosdion** 2023-10-29 08:16 UTC
Labels: duplicate
