### ISSUE TITLE
Users with only Add Own and Edit Own privileges cannot add sites

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#203] opened 2023-10-30 17:22 UTC
Nicholas I confirm the problem #197 but "change the title of this issue": it is NON superusers who are unable to create sites.

In past tests I did a test with the same site, deleting it with the Superuser account and trying to create it later with a NON superuser user account without success.

I managed to insert the deleted sites again without problems, but only with a superuser account.
While NON superuser accounts receive a "403 error - Access Denied" even with the "ADD OWN" and "EDIT OWN" options enabled when attempting to add a site.

**Comment by nikosdion** [comment] 2023-10-30 17:29
If you give the user the View privilege, can they add a site?

Note that whether that site (more correctly: that Endpoint URL) existed in the past or not is irrelevant since that record has been deleted.

**Comment by morphinestyle** [comment] 2023-10-30 17:34
If I enable View privilege the user can also see the sites that I have put in another group and which he should not see.

**Comment by morphinestyle** [comment] 2023-10-30 17:40
If for a user I select Add Own and Edit Own i expect user can't view all others (unless I enable View)

**Comment by morphinestyle** [comment] 2023-10-30 17:46
> If you give the user the View privilege, can they add a site?
> 
> Note that whether that site (more correctly: that Endpoint URL) existed in the past or not is irrelevant since that record has been deleted.

No, also vith Administrator, View and Execute as non-Superuser i can't add a website.

**Comment by nikosdion** [comment] 2023-10-30 17:51
Yes, of course I understand what privileges do and what you expect of them — I documented these expectations myself, remember? I asked a question so I could narrow it down to either something I already fixed in the ACL system, or a bug I have not seen yet.

Based on your feedback, you _seem_ to be affected by the issue I fixed in https://github.com/akeeba/panopticon/commit/69465c8afa693886bf76713cbca29ab7e7c500db  How can I tell? With that patch applied, I have a user with only Administrator and View privileges which can add sites. Since our only difference is that path, it would appear that its absence is what causes the problem in your case.

Can you please apply the changes from the aforementioned commit to your installation and tell me if a user with just Add Own and Edit Own privileges can add a site? If they can, cool, the problem is already solved. If not, well, there's a new bug I have to chase.

**Comment by morphinestyle** [comment] 2023-10-30 17:59
I replaced the ACLTrait.php file but nothing change.

I get:
There was an unrecoverable error
The server returned the following error:
403 — Accesso Negato

**Closed** 2023-10-31 09:33 UTC
