### ISSUE TITLE
mail messages amount en details

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#237] opened 2023-11-06 10:50 UTC
i am doing some testing regarding mail messages on core and extention updates.
currently i have 10 sites configured in Panopticon.

now, on every update from every site i get every hour a mail message (1 for every update available).
would be nice (in de future) to have options to configure regarding the amount of messages.
lets say, - 
one mail with all updates from all sites combined
- reporting only once regarding a available update.. (currently every hour i get the same messages).
- mail message one per site with core and/or extion updates (combined)

currently i have only one site that is not up to date and configured as notify by mail and not automatic update for testing reasons.
not al the sites / situations are right for automatic update's.
the amount of messages should be les.. so check every hour, mail messages once a day for expample.

etc.etc.

**Comment by nikosdion** [comment] 2023-11-06 16:32
This was a bug that is already fixed with https://github.com/akeeba/panopticon/commit/6c869f4bd63cc35fddad5328e363d83b80b481e5

**Closed by nikosdion** 2023-11-06 16:32 UTC
Labels: duplicate, request

**Comment by johanpeters** [comment] 2023-11-06 19:09
what bug was fixed in 1.0.3.
i configured mail message for extention update's.. it still reporting every extention update in a seperate mail.

**Comment by nikosdion** [comment] 2023-11-06 19:37
Each extension does get its own email. This is by design and we've already talked about how it can only change if I implement the feature you suggested in #220 

You were saying that each of these emails was sent every hour. It's not longer sent every hour, it is sent **ONCE**. This is what was fixed in 1.0.3.
